name: S3 deploy with cloud front
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env: 
          REACT_APP_API_SERVER: ${{ secrets.REACT_APP_API_SERVER }}
          REACT_APP_AUTH: ${{ secrets.REACT_APP_AUTH }}
          REACT_APP_AUTH_PW: ${{ secrets.REACT_APP_AUTH_PW }} 
          REACT_APP_OPENVIDU_SERVER_URL: ${{ secrets.REACT_APP_OPENVIDU_SERVER_URL }}
          REACT_APP_OPENVIDU_SERVER_SECRET: ${{ secrets.REACT_APP_OPENVIDU_SERVER_SECRET }}
          REACT_APP_API_KAKAO_KEY: ${{ secrets.REACT_APP_API_KAKAO_KEY }}

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
